import { StyleSheet } from "react-native";

const colors = {
  primary: "#55A57F",
  secondary: "#7C6DDD",
  dark: "#333",
  white: "#fff",
  gray: "#999",
  lightGray: "#F2F2F2",
  border: "#ddd",
  error: "#FF0000",
  button: "#34D186",
  black: "#000000",
};

export const HomePage = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
    marginBottom: 0,
  },
  greetingSection: {
    backgroundColor: colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 40,
    // borderBottomLeftRadius: 20,
    // borderBottomRightRadius: 20,
    position: "relative",
    height: 210,
  },
  greetingText: {
    fontSize: 26,
    fontWeight: "bold",
    color: "white",
    marginBottom: 8,
    marginTop: 15,
  },
  subText: {
    fontSize: 16,
    color: "white",
    marginTop: 0,
  },
  notificationIcon: {
    position: "absolute",
    top: -50,
    right: 0,
    color: "white",
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingVertical: 20,
    backgroundColor: "white",
    marginHorizontal: 20,
    marginTop: -60,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 2,
    height: 132,
  },
  statBox: {
    alignItems: "center",
  },
  statLabel: {
    fontSize: 14,
    color: colors.gray,
    textAlign: "center",
  },
  statValue: {
    fontSize: 24,
    fontWeight: "bold",
    color: colors.secondary,
    marginTop: 15,
  },
  scheduleButton: {
    flexDirection: "row",
    backgroundColor: colors.secondary,
    paddingVertical: 15,
    marginHorizontal: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
  },
  scheduleButtonText: {
    fontSize: 16,
    color: "white",
    marginLeft: 10,
  },
  upcomingContainer: {
    padding: 20,
    marginTop: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 10,
  },
  scrollViewContent: {
    paddingBottom: 550,
  },
  pickupCard: {
    backgroundColor: "white",
    paddingVertical: 20,
    paddingHorizontal: 15,
    borderRadius: 12,
    marginHorizontal: 0,
    marginBottom: 15,
    alignItems: "center",
    flexDirection: "row",
    width: "100%",
    borderColor: colors.gray,
    borderWidth: 1,
    overflow: "hidden",
  },

  truckIcon: {
    width: 80,
    height: 50,
  },
  pickupDate: {
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 10,
    marginHorizontal: 20,
  },
  pickupTime: {
    fontSize: 16,
    color: colors.gray,
    marginHorizontal: 20,
    marginTop: 5,
  },
  animationContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: -30,
  },
  lottieAnimation: {
    width: 250,
    height: 250,
  },
  noDataText: {
    fontSize: 20,
    color: colors.black,
    marginTop: 20,
    fontWeight: "bold",
  },
  noDatasubText: {
    fontSize: 16,
    color: colors.gray,
    marginTop: 10,
  },
});


export const SchedulePage = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    marginBottom: 80,
  },
  header: {
    backgroundColor: '#55A57F',
    paddingHorizontal: 20,
    paddingVertical: 40,
    // borderBottomLeftRadius: 20,
    // borderBottomRightRadius: 20,
    position: 'relative',
    height: 140,
  },
  title: {
    fontSize: 26,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 0,
    marginTop: 15,
  },
  subtitle: {
    fontSize: 16,
    color: 'white',
  },
  notificationIconWrapper: {
    position: 'absolute',
    top: 50,
    right: 20,
  },
  notificationIcon: {
    color: 'white',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000', 
    marginTop: 20,
    marginBottom: 10,
    marginHorizontal: 20,
  },
  scheduleCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    padding: 10,
    borderRadius: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  binImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 15,
  },
  binDetails: {
    flex: 1,
    justifyContent: 'space-between',
  },
  scheduleDate: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 2,
  },
  scheduleTime: {
    fontSize: 14,
    color: '#888',
    marginBottom: 4,
  },
  binInfo: {
    fontSize: 12,
    color: '#777',
  },
  binPrice: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'red',
    marginTop: 6,
  },
  scrollContainer: {
    flexGrow: 1,
  },
  scheduleList: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  addButton: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    backgroundColor: '#7C6DDD',
    borderRadius: 30,
    width: 60,
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  animationContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: -30,
  },
  lottieAnimation: {
    width: 250,
    height: 250,
  },
  noDataText: {
    fontSize: 20,
    color: colors.black,
    marginTop: 20,
    fontWeight: "bold",
  },
  noDatasubText: {
    fontSize: 16,
    color: colors.gray,
    marginTop: 10,
  },
});

export const AddScheduleStyles = StyleSheet.create({

  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  checkboxContainer: {
    marginTop: 10,
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginHorizontal: 10,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  checkboxText: {
    marginLeft: 10,
    fontSize: 16,
    color: '#7C6DDD',
  },
  binContainer: {
    marginTop: 20,
    paddingHorizontal: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000', 
    marginTop: 20,
    marginBottom: 10,
    marginHorizontal: 10,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginBottom: 10,
  },
  editText: {
    color: '#7C6DDD',
    marginRight: 5,
    fontSize: 16,
    fontWeight: 'bold',
  },
  scheduleCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    padding: 10,
    borderRadius: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  binImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 15,
  },
  binDetails: {
    flex: 1,
    justifyContent: 'space-between',
  },
  scheduleDate: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 2,
  },
  binInfo: {
    fontSize: 12,
    color: '#777',
  },
  binPrice: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#34D186',
    marginTop: 6,
  },
  addressContainer: {
    marginTop: 10,
    paddingHorizontal: 20,
  },
  addressCard: {
    backgroundColor: 'white',
    padding: 15,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 2,
  },
  addressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  addressText: {
    marginLeft: 5,
    fontSize: 16,
    fontWeight: 'bold',
  },
  fullAddress: {
    fontSize: 14,
    color: '#888',
    marginTop: 5,
    paddingHorizontal: 25,
  },
  addressCode: {
    fontSize: 14,
    color: '#A11843',
    marginTop: 5,
    fontWeight: 'bold',
    paddingHorizontal: 25,
  },
  scheduleButton: {
    backgroundColor: '#7C6DDD',
    padding: 15,
    marginHorizontal: 20,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 90,
  },
  scheduleButtonText: {
    color: 'white',
    fontSize: 16,
    marginLeft: 10,
  },
  modalBackground: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContainer: {
    width: '80%',
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  daySelection: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    marginBottom: 20,
  },
  dayButton: {
    backgroundColor: 'white',
    borderColor: '#7C6DDD',
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    margin: 5,
  },
  dayButtonSelected: {
    backgroundColor: '#7C6DDD',
  },
  dayButtonText: {
    fontSize: 14,
    color: '#7C6DDD',
  },
  confirmButton: {
    backgroundColor: '#7C6DDD',
    padding: 10,
    borderRadius: 10,
    width: '100%',
    alignItems: 'center',
    marginTop: 50,
  },
  confirmButtonText: {
    color: 'white',
    fontSize: 16,
  },
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    paddingTop: 50,
    paddingHorizontal: 30,
  },
  // repeatInfo: {
  //   marginBottom: 20,
  //   marginTop: -10,
  //   fontSize: 14,
  //   color: '#888',
  // },
  binContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 10,
  },
  selectedBin: {
    borderColor: '#34D186',
    borderWidth: 2,
  },
  binImage: {
    width: 50,
    height: 50,
    marginRight: 15,
  },
  binDetails: {
    flex: 1,
  },
  binName: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  binSize: {
    fontSize: 14,
    color: '#555',
  },
  binBags: {
    fontSize: 12,
    color: '#777',
  },
  closeButton: {
    position: 'absolute',
    top: -70,
    right: 5,
    padding: 5,
    backgroundColor: '#D9D9D9',
    borderRadius: 15,
    width: 25,
    height: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 1,
  },
  closeButtonText: {
    fontSize: 16,
    color: '#000',
    fontWeight: 'bold',
    alignSelf: 'center',  
  },
  price: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#34D186',
    marginTop: 5,
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  quantityButton: {
    fontSize: 10,
    padding: 10,
    backgroundColor: '#5555',
    textAlign: 'center',
    borderRadius: 5,
  },
  quantityText: {
    fontSize: 16,
    paddingHorizontal: 15,
  },
  proceedButton: {
    backgroundColor: '#7C6DDD',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 20,
  },
  proceedText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
});